C2C-78:Add database and file backup cronjobs
mekomsolutions/k8s-description-files pull request #14
Opened 2021-03-28 11:08 UTC by enyachoke

2021-04-09 07:23 UTC, rbuisson requested changes
Thanks. Few comments.

2021-04-09 07:23 UTC, rbuisson commented on src/bahmni-helm/templates/apps/backup-services/cron-jobs.yml
> +  name: {{ .Release.Name }}-firestore-backup
`firestore`!
->`filestore`

2021-04-09 07:23 UTC, rbuisson commented on src/bahmni-helm/templates/apps/backup-services/cron-jobs.yml
> +  name: {{ .Release.Name }}-postres-backup
`{{ .Release.Name }}-postres-backup` seems like it should be named `{{ .Release.Name }}-odoo-db-backup`

2021-04-09 07:23 UTC, rbuisson commented on src/bahmni-helm/templates/apps/backup-services/cron-jobs.yml
> +  name: {{ .Release.Name }}-mysql-backup
`{{ .Release.Name }}-mysql-backup` seems like it should be named `{{ .Release.Name }}-openmrs-db-backup`

2021-04-09 07:23 UTC, rbuisson commented on src/bahmni-helm/templates/apps/backup-services/cron-jobs.yml
> +          - name: {{ .Release.Name }}-firestore-backup
`filestore`

2021-04-09 07:23 UTC, rbuisson commented on src/bahmni-helm/templates/apps/backup-services/cron-jobs.yml
> +          - name: {{ .Release.Name }}-firestore-backup
What does this service backs up?

2021-04-09 07:23 UTC, rbuisson commented on src/bahmni-helm/templates/apps/backup-services/cron-jobs.yml
> +  name: {{ .Release.Name }}-openelis-backup
`{{ .Release.Name }}-openelis-db-backup`

2021-04-14 06:48 UTC, rbuisson requested changes
typo

2021-04-14 06:48 UTC, rbuisson commented on src/bahmni-helm/templates/apps/backup-services/cron-jobs.yml
> +              subPath: "postres"
post**g**res

2021-04-15 01:27 UTC, enyachoke commented
_typo: postres -> postgres_  I renamed the subpath as well.

2021-04-16 14:00 UTC, rbuisson approved these changes

2021-04-16 14:00 UTC, merged